<?php

namespace BK\PlatformBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EnregistrementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnregistrementRepository extends EntityRepository
{
}
